-- ============================================
-- SUPABASE DATABASE SCHEMA
-- Run this in your Supabase SQL Editor
-- ============================================

-- Create batches table
CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create members table
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    locale TEXT,
    voice TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create attendance table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    category TEXT NOT NULL,
    event TEXT NOT NULL,
    status TEXT NOT NULL,
    reason TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_members_batch_id ON members(batch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_batch_id ON attendance(batch_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(date);
CREATE INDEX IF NOT EXISTS idx_batches_is_current ON batches(is_current);

-- Insert default Batch13 if no batches exist
INSERT INTO batches (name, is_current)
SELECT 'Batch13', TRUE
WHERE NOT EXISTS (SELECT 1 FROM batches LIMIT 1);

-- ============================================
-- DATA MIGRATION (Optional)
-- Only run if you want to migrate existing data from Google Sheets
-- ============================================

-- To migrate members from Google Sheets:
-- 1. Export your Google Sheet data as CSV
-- 2. Use Supabase Dashboard > Table Editor > members > Import data

-- To migrate attendance records:
-- 1. Export each batch's attendance sheet as CSV
-- 2. Use Supabase Dashboard > Table Editor > attendance > Import data
-- 3. Make sure to set the correct batch_id for each record
